baseURL = "https://masatakashiwagi.github.io/mlops-practices/"
languageCode = "ja"
title = "MLOps - Practices"
theme = "cactus"
copyright = "masatakashiwagi"
googleAnalytics = "UA-217356001-1"
enableEmoji = true
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Github Pagesでwebページを公開する用
publishDir = "docs"

# summaryLength = 2

# Main menu which appears below site header.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Knowledge"
    url = "/knowledge"
    weight = 2

  [[menu.main]]
    name = "Tips"
    url = "/tips"
    weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true

[params]
  author = "Masataka Kashiwagi"
	subtitle = "MLOpsに対する各社の取り組みを整理したDocs"
	keywords = "MLOps,機械学習,Machine Learning"

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  googleAnalyticsTid = "UA-217356001-1"
  googleAnalyticsRoute = "https://masatakashiwagi.github.io/mlops-practices/"
  showAllPostsArchive = false # default

  # Home page settings
  description = "MLOpsに対して，&nbsp;各社が取り組んでいる内容や知見を集めたものになります．&nbsp;各社のテックブログや登壇での発表資料を中心に&nbsp;「**Knowledge**」&nbsp;に整理しています．&nbsp;また，&nbsp;個人ブログでの発信内容については，&nbsp;サービスやプロダクトの&nbsp;「**Tips**」&nbsp;として別で整理する予定です．"
  mainSection = "home" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/masatakashiwagi/mlops-practices"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/asteriam_fp"
  [[params.social]]
    name = "rss"
    link = "https://masatakashiwagi.github.io/mlops-practices/index.xml"
